---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - experimental.milkshakes.cloud.milkshakes.cloud
  resources:
  - frpgcpremotes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - experimental.milkshakes.cloud.milkshakes.cloud
  resources:
  - frpgcpremotes/finalizers
  verbs:
  - update
- apiGroups:
  - experimental.milkshakes.cloud.milkshakes.cloud
  resources:
  - frpgcpremotes/status
  verbs:
  - get
  - patch
  - update
